image:
  file: .gitpod.Dockerfile

ports:
  - port: 3306
    visibility: public
    onOpen: ignore

  - port: 8888
    visibility: public
    onOpen: ignore

  - port: 8080
    visibility: public
    onOpen: ignore