image:
  file: .gitpod.Dockerfile

ports:
  - port: 3306
    visibility: public
    onOpen: ignore

  - port: 5005
    visibility: public
    onOpen: ignore

  - port: 5555
    visibility: public
    onOpen: ignore    

  - port: 8080
    visibility: public
    onOpen: ignore

  - port: 8888
    visibility: public
    onOpen: ignore

vscode:
  extensions:
    - vscjava.vscode-java-pack
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-dependency
    - vscjava.vscode-java-test
    - vscjava.vscode-maven
    - redhat.java
    - redhat.fabric8-analytics
    - ms-azuretools.vscode-docker
    - mathiasfrohlich.kotlin
    - hashicorp.terraform

